```bash
#!/bin/bash
set -euo pipefail

# Script: Proxmox Network Configuration
# Description: This script configures network bridges on Proxmox VE.
# It sets up vmbr0 (with optional static IP or DHCP), vmbr1 (NAT with DHCP via dnsmasq),
# and vmbr10 (static internal bridge). Assumes /24 subnets for simplicity.
# Author: Optimized by Grok
# Version: 1.0
# Usage: Run as root on Proxmox host.

echo "=== Proxmox Network Configuration Script ==="

# Default values
DEFAULT_PHY_IFACE="ens33"

# Prompt for physical interface
read -p "Enter the physical interface for vmbr0 [$DEFAULT_PHY_IFACE]: " PHY_IFACE
PHY_IFACE=${PHY_IFACE:-$DEFAULT_PHY_IFACE}
echo "Using physical interface: $PHY_IFACE"

# Prompt for subnets (assuming /24)
read -p "Enter vmbr1 subnet base (e.g., 192.168.100): " VMBR1_SUBNET_BASE
read -p "Enter vmbr10 subnet base (e.g., 10.50.1): " VMBR10_SUBNET_BASE

# Calculate IPs and networks
VMBR1_IP="${VMBR1_SUBNET_BASE}.1/24"
VMBR1_NET="${VMBR1_SUBNET_BASE}.0/24"
VMBR1_DHCP_START="${VMBR1_SUBNET_BASE}.50"
VMBR1_DHCP_END="${VMBR1_SUBNET_BASE}.200"

VMBR10_IP="${VMBR10_SUBNET_BASE}.1/24"

# Option for static IP on vmbr0
read -p "Set static IP for vmbr0? (y/n) [n]: " SET_STATIC_VMBR0
SET_STATIC_VMBR0=${SET_STATIC_VMBR0:-n}

if [[ "$SET_STATIC_VMBR0" =~ ^[Yy]$ ]]; then
  read -p "Enter vmbr0 static IP (e.g., 192.168.50.6/24): " VMBR0_IP
  read -p "Enter vmbr0 gateway IP (e.g., 192.168.50.1): " VMBR0_GATEWAY

  VMBR0_CONFIG="iface vmbr0 inet static
    address $VMBR0_IP
    gateway $VMBR0_GATEWAY"
  VMBR0_SUMMARY="vmbr0: Static IP $VMBR0_IP, gateway $VMBR0_GATEWAY via $PHY_IFACE"
else
  VMBR0_CONFIG="iface vmbr0 inet dhcp"
  VMBR0_SUMMARY="vmbr0: DHCP via $PHY_IFACE"
fi

# Backup existing interfaces file
TIMESTAMP=$(date +%s)
BACKUP_FILE="/etc/network/interfaces.bak.$TIMESTAMP"
cp /etc/network/interfaces "$BACKUP_FILE"
echo "Backed up /etc/network/interfaces to $BACKUP_FILE"

# Generate new interfaces configuration
cat <<EOF > /etc/network/interfaces
# This file was generated by Proxmox Network Configuration Script

auto lo
iface lo inet loopback

auto $PHY_IFACE
iface $PHY_IFACE inet manual

auto vmbr0
$VMBR0_CONFIG
    bridge-ports $PHY_IFACE
    bridge-stp off
    bridge-fd 0

source /etc/network/interfaces.d/*

auto vmbr1
iface vmbr1 inet static
    address $VMBR1_IP
    bridge-ports none
    bridge-stp off
    bridge-fd 0
    post-up echo 1 > /proc/sys/net/ipv4/ip_forward
    post-up iptables -t nat -A POSTROUTING -s '$VMBR1_NET' -o vmbr0 -j MASQUERADE
    post-down iptables -t nat -D POSTROUTING -s '$VMBR1_NET' -o vmbr0 -j MASQUERADE

auto vmbr10
iface vmbr10 inet static
    address $VMBR10_IP
    bridge-ports none
    bridge-stp off
    bridge-fd 0
EOF

echo "Updated /etc/network/interfaces"

# Install required packages if not already installed
echo "Installing required packages..."
apt update -y
apt install -y --no-install-recommends dnsmasq iptables-persistent netfilter-persistent

# Configure dnsmasq for vmbr1
DNSMASQ_CONF="/etc/dnsmasq.d/vmbr1.conf"
cat <<EOF > "$DNSMASQ_CONF"
interface=vmbr1
bind-interfaces
dhcp-range=$VMBR1_DHCP_START,$VMBR1_DHCP_END,12h
dhcp-option=3,${VMBR1_SUBNET_BASE}.1
dhcp-option=6,8.8.8.8,1.1.1.1
EOF

echo "Configured dnsmasq at $DNSMASQ_CONF"

# Enable and restart services
systemctl enable dnsmasq
systemctl restart dnsmasq
netfilter-persistent save || true  # Save iptables rules

# Apply network changes
echo "Applying network configuration..."
ifup -a || true  # Bring up interfaces if not already
systemctl restart networking || {
  echo "Networking restart failed. Rebooting system..."
  reboot
}

echo "=== Configuration Complete ==="
echo "$VMBR0_SUMMARY"
echo "vmbr1: $VMBR1_IP, DHCP range $VMBR1_DHCP_START - $VMBR1_DHCP_END"
echo "vmbr10: $VMBR10_IP"
echo "Note: Verify connectivity after changes. If issues arise, restore from backup: $BACKUP_FILE"
```